import { EventPattern, EventType } from './types';

export const EVENT_PATTERNS: Record<EventType, EventPattern> = {
  APPLICATION_RECEIVED: {
    subjectKeywords: [
      'application received',
      'application confirmation',
      'we received your application',
      'your application for',
      'application submitted',
      'thank you for your interest',
    ],
    keywords: [
      'application received',
      'received your application',
      'thank you for applying',
      'application confirmed',
      'submitted successfully',
      'thank you for your interest in',
      'we have received your resume',
      'your application has been submitted',
      'application is under review',
      'reviewing your application',
      'thank you for taking the time to apply',
      'we appreciate your interest',
      'your application is being reviewed',
      'application status: received',
      'successfully applied',
      'your resume has been received',
      'we look forward to reviewing your application',
      'you have successfully submitted your application',
      'we will review your qualifications',
      'your application has been forwarded',
      'acknowledged receipt of your application',
    ],
    negativeKeywords: [
      'unfortunately',
      'regret to inform',
    ],
    weight: 1.0,
  },

  INTERVIEW_REQUEST: {
    subjectKeywords: [
      'interview invitation',
      'interview request',
      'scheduling your interview',
      'next steps in your application',
      'interview opportunity',
    ],
    keywords: [
      'schedule an interview',
      'interview availability',
      'would you be available',
      'invite you to interview',
      'interview invitation',
      'like to set up a time',
      'please share your availability',
      'when are you free',
      'what times work for you',
      'next step in the interview process',
      'would love to chat',
      'would like to have a conversation',
      'phone screen',
      'initial call',
      'introductory call',
      'move you forward to the interview stage',
      'like to discuss this opportunity',
      'please provide your availability',
      'book a time to speak',
      'select a time that works for you',
      'schedule a call',
      'we are excited to move forward',
    ],
    negativeKeywords: [
      'cancelled',
      'unfortunately',
    ],
    weight: 1.0,
  },

  INTERVIEW_SCHEDULED: {
    subjectKeywords: [
      'interview confirmed',
      'interview scheduled',
      'your interview on',
      'upcoming interview',
      'meeting confirmed',
      'calendar invite',
    ],
    keywords: [
      'interview scheduled',
      'interview confirmed',
      'see you on',
      'meeting has been scheduled',
      'calendar invite',
      'your interview is confirmed for',
      'you are confirmed for',
      'join link',
      'zoom link',
      'google meet',
      'microsoft teams meeting',
      'dial-in information',
      'interview details',
      'please join',
      'the interview will take place on',
      'you will be meeting with',
      'your interview panel',
      'interview agenda',
      'please arrive at',
      'meeting invite sent',
    ],
    negativeKeywords: [
      'cancelled',
      'rescheduled',
    ],
    weight: 1.0,
  },

  ASSESSMENT: {
    subjectKeywords: [
      'coding challenge',
      'technical assessment',
      'take-home assignment',
      'skills assessment',
      'online assessment',
      'complete your assessment',
    ],
    keywords: [
      'coding challenge',
      'technical assessment',
      'complete the assessment',
      'take-home assignment',
      'hackerrank',
      'codility',
      'coderpad',
      'leetcode',
      'online assessment',
      'timed assessment',
      'coding test',
      'skills test',
      'please complete the following',
      'assessment link',
      'assessment deadline',
      'you have been invited to take',
      'test your skills',
      'complete this exercise',
      'pair programming',
      'system design exercise',
      'case study',
      'work sample',
    ],
    weight: 1.0,
  },

  OFFER: {
    subjectKeywords: [
      'offer letter',
      'job offer',
      'offer of employment',
      'welcome to the team',
      'your offer from',
    ],
    keywords: [
      'offer letter',
      'pleased to offer',
      'extend an offer',
      'compensation package',
      'offer of employment',
      'pleased to inform you',
      'delighted to extend',
      'formal offer',
      'starting salary',
      'base salary',
      'annual compensation',
      'equity grant',
      'signing bonus',
      'we are thrilled to offer you',
      'welcome aboard',
      'contingent upon background check',
      'please review and sign',
    ],
    negativeKeywords: [
      'rescind',
      'withdraw',
    ],
    weight: 1.0,
  },

  REJECTION: {
    subjectKeywords: [
      'update on your application',
      'regarding your application',
      'your application status',
      'application update',
    ],
    keywords: [
      'unfortunately',
      'decided to move forward with other candidates',
      'not moving forward',
      'position has been filled',
      'will not be proceeding',
      'regret to inform you',
      'after careful consideration',
      'we have decided to pursue other candidates',
      'not the right fit',
      'will not be moving forward',
      'we are unable to offer you',
      'competitive pool of applicants',
      'other candidates whose experience',
      'wish you all the best',
      'encourage you to apply again',
      'keep your resume on file',
      'we appreciate your time and effort',
      'not selected for',
      'chosen not to move forward',
      'not to move forward',
      'at this time we are unable',
      'we will not be extending',
      'candidacy has been closed',
      'encourage you to apply',
    ],
    weight: 1.0,
  },

  RECRUITER_OUTREACH: {
    subjectKeywords: [
      'exciting opportunity',
      'opportunity at',
      'role you might be interested in',
      'reaching out',
      'your profile',
      'perfect fit',
    ],
    keywords: [
      'recruiting',
      'opportunity that might interest you',
      'reaching out regarding',
      'potential opportunity',
      'interested in connecting',
      'came across your profile',
      'impressed by your background',
      'thought of you for',
      'passive candidate',
      'talent acquisition',
      'on behalf of my client',
      'confidential search',
      'exclusive opportunity',
      'your linkedin profile',
      'would you be open to',
      'exploring new opportunities',
      'competitive compensation',
      'top-tier company',
      'are you currently looking',
      'i represent',
      'hiring for',
      'great match for',
    ],
    senderDomains: [
      'linkedin.com',
      'indeed.com',
      'ziprecruiter.com',
      'glassdoor.com',
      'dice.com',
      'hired.com',
      'otta.com',
      'wellfound.com',
    ],
    weight: 1.0,
  },

  OTHER: {
    subjectKeywords: [],
    keywords: [],
    weight: 0.0,
  },
};
